# Augusta Kit Documentation
<!-- Sources: Wuthering Waves Fandom Wiki, Prydwen.gg, Game8.co, Wutheringlab.com, Wuthering.gg, Destructoid, Sportskeeda, LootBar.gg, DBLTap, WuWaCompanion, FdayTalk -->

## Augusta: Combat Archetype and Role
- **Element/Attribute:** Electro
- **Weapon Type:** Broadblade
- **Role:** Main DPS — on-field sustained and burst damage dealer
- **Scaling Stat:** ATK (primary); Crit Rate and Crit DMG (critical multipliers)
- **Damage Type:** Heavy Attack DMG (the vast majority of her damage — approximately 77% — is classified as Heavy Attack DMG, even during Liberation)
- **Combat Style:** Resource-management brawler — manages three parallel Forte resources (Prowess, Ascendancy, Majesty) to cycle through enhanced Heavy Attacks, an Enhanced Resonance Skill combo, and a time-stopping Liberation. Her rotation rewards players who understand her resource interplay and can optimize sequencing.
- **Specialty:** Time-stop Liberation (Sworn Allegiance) that physically pauses all in-game timers — including endgame content timers in Tower of Adversity and Whimpering Wastes — for 7 full seconds. Augusta is one of very few characters in Wuthering Waves whose ultimate literally stops time.

## Augusta: Key Resources (Forte Mechanics Overview)

## Augusta Forte Circuit: Prowess, Ascendancy, and Majesty
Augusta's Forte Circuit manages three distinct and interdependent resources simultaneously.

**1. Prowess (Purple Bar — Max 100):**
- Generated by: Basic Attacks, Heavy Attack – Steelclash, Mid-air Attack, Mid-air Dodge Counter, Resonance Skill – Warrior's Blade, Dodge Counter, Dodge Counter – Heavy Attack: Steelclash
- Instantly refilled by: Casting Intro Skill – Stride of Goldenflare
- When full (100): Heavy Attack – Steelclash is replaced by Heavy Attack – Thunderoar: Backstep (consuming all Prowess), enabling the Spinslash and Uppercut chain. Dodge Counter is replaced by Dodge Counter – Thunderoar: Backstep.
- Design note: The Backstep has a low ~50% ATK multiplier, but serves as the trigger for the Spinslash which exceeds 400% ATK. An interruption compensation mechanism allows the Spinslash to still fire even if the Backstep is interrupted.

**2. Ascendancy (Gold Circle — Max 100):**
- Generated by: Normal Attacks dealing damage
- Restored by: Intro Skill (20%), Resonance Skill – Warrior's Blade (10%), Resonance Liberation – Sword of Eternal Oath (40%)
- When full (100): Resonance Skill becomes Resonance Skill – Undying Sunlight: Strike, unlocking the three-part aerial combo (Strike → Leap → Plunge). The crown icon on the Forte bar glows, matching Augusta's sunburst headpiece visually.
- Design note: Ascendancy is the gateway to Majesty — the Enhanced RS chain must be completed, concluding in Undying Sunlight: Plunge, to gain 1 Majesty stack.

**3. Majesty (Gold Blade Icons — Max 2 stacks):**
- Gained from: Casting Resonance Skill – Undying Sunlight: Plunge (1 stack); incoming Resonator casting Outro Skill while under Augusta's Outro buff (1 stack via Battlesong of the Unyielding)
- Passive restoration: If Augusta is out of combat for 4+ seconds and has fewer than 1 Majesty stack, 1 stack is restored automatically (triggered once every 4s)
- Crown of Wills (S0 max 1 stack; S1 max 2; S6 max 4): At S0, 1 stack = 15% Electro DMG Bonus. Gained via Outro Skill. Consumed when Sublime is the Sun – Everbright Protector ends. Also restored by out-of-combat passive.
- At 2 Majesty stacks: Hold Resonance Liberation to cast Resonance Liberation – Sublime is the Sun (consuming 2 Majesty, not Resonance Energy), entering the Sworn Allegiance time-stop state.

## Augusta: Inherent Passives
**Inherent Skill 1 – Glory's Favor:**
When Augusta deals damage, she gains a shield equal to 350 + 2.5% of her Max HP for 5 seconds, triggered once every 0.5 seconds. This shield is not passed to incoming Resonators. This is Augusta's auto-shield — it fires constantly during combat, fueling both her signature weapon and Crown of Valor echo set at near-maximum uptime.

**Inherent Skill 2 – Blazing Valor (Passive Out-of-Combat Recovery):**
When Augusta is out of combat for over 4 seconds, the following effects trigger once every 4 seconds:
- If Majesty is less than 1 stack, restore 1 stack of Majesty.
- Fully restore all stacks of Crown of Wills.
This means Augusta enters each fight with her resources partially pre-loaded, reducing ramp-up time between rotations.

---

## Augusta: Stats Baseline: Level 1 – 90
*Base stats only. Does not include Forte Attribute Bonuses (Electro DMG +12%, ATK% +12% from nodes). Weapon not included.*

| Level | HP       | ATK  | DEF  |
|-------|----------|------|------|
| 1     | ~858     | ~28  | ~91  |
| 10    | ~2,097   | ~68  | ~222 |
| 20    | ~3,892   | ~125 | ~412 |
| 30    | ~5,565   | ~178 | ~589 |
| 40    | ~7,242   | ~231 | ~767 |
| 50    | ~9,108   | ~291 | ~964 |
| 60    | ~10,920  | ~349 | ~1,156|
| 70    | ~12,600  | ~402 | ~1,333|
| 80    | ~13,900  | ~444 | ~1,471|
| 90    | ~14,283  | ~457 | ~1,512|

*Note: Exact per-level breakpoints are not publicly listed in official documentation. Figures above are approximate community extrapolations. The Lv.90 base character ATK is confirmed at approximately 457 from community sources.*

## Augusta: Stats Baseline: Max Analysis
**Level 90 Confirmed Stats (S0, no echoes, with Forte Attribute Bonuses):**
- HP: ~14,283 (base)
- ATK: ~457 (base character ATK, before weapon); confirmed base ATK (Lv.90) from WuWaCompanion: 675 (this is combined character + weapon base at Lv.90 with Thunderflare Dominion)
- DEF: ~1,512 (approx)
- Base CRIT Rate: 5%
- Base CRIT DMG: 150%
- Max Energy: 125
- Forte Attribute Bonuses at max nodes: +12% Electro DMG Bonus, +12% ATK%

**Recommended Endgame Stats (S0, per Prydwen and Game8):**
- ATK: 2,100+ (minimum; higher is better)
- CRIT Rate: 70–80% (to achieve consistent crits; lower threshold than most DPS due to Crown of Wills Electro DMG Bonus making extra CRIT DMG valuable at S2)
- CRIT DMG: ~220–250% (target; Crown of Valor adds up to +20% additional)
- Heavy Attack DMG Bonus: as high as possible from substats

**Signature Weapon – Thunderflare Dominion (R1, Lv.90):**
- Base ATK: 675
- Secondary Stat: CRIT Rate 12.2%
- Passive R1: ATK +12%. Casting Intro Skill or Resonance Skill increases Heavy Attack DMG by +20% for 15s. Obtaining Shield allows Heavy Attack DMG to ignore 7.2% of the target's DEF for 7s, stacking up to 5 times (triggered once every 0.5s). Maximum DEF ignore at 5 stacks: 36%.
- Passive R5: ATK +24%. Heavy Attack DMG +40% for 15s. DEF ignore 12% per shield gain, up to 5 stacks (60% total).

## Augusta: Ascension Materials
Full Ascension (Lv.1 → Lv.90):

- **Luminous Calendula** (~60 total): Local specialty of Septimont, found specifically in the Sanguis Plateaus area of Rinascita. Cannot be pre-farmed before Version 2.6 release. Can be obtained from the Interactive Map.
- **When Irises Bloom** (Weekly Boss drop): Dropped by Fleurdelys — the Version 2.6 Weekly Boss. Approximately 14–16 required for full ascension.
- **Blighted Crown of Puppet King** (Boss material): Specific boss drop from Septimont-region bosses.
- **LF / MF / HF / FF Tidal Residuum** (enemy drops): Standard Rinascita enemy drops; ascending tiers required at each ascension level.
- **Waveworn Residue** series (210, 226, 235, 239): Obtained from Forgery Challenges or purchasable in cities.
- **Shell Credits:** Approximately 170,000 for full ascension to Lv.90.

---

## Augusta: Character Kit

## Augusta Basic Attack: Blade of the Sun
Perform up to 4 consecutive attacks dealing Electro DMG.

- **Stage 1:** Single downward slash, Electro DMG
- **Stage 2:** Wide sweeping slash, Electro DMG
- **Stage 3:** Overhead slam, Electro DMG
- **Stage 4:** Powerful forward sweep, Electro DMG
- **Heavy Attack – Steelclash:** Consume STA to attack the target, dealing Electro DMG. Press Normal Attack shortly after to perform Basic Attack Stage 2.
- **Heavy Attack – Thunderoar: Backstep (Prowess Full):** When Prowess is full, Heavy Attack – Steelclash is replaced. Augusta steps back dealing Electro DMG, consuming all Prowess. Input Normal Attack again within a brief window to perform Thunderoar: Spinslash. If Backstep is interrupted, Spinslash can still be triggered (interruption compensation).
- **Heavy Attack – Thunderoar: Spinslash:** Augusta whirls and lashes with her Broadblade, dealing Electro DMG. The Spinslash is the primary damage portion (~400%+ ATK multiplier). The Spinslash's endlag can be cancelled by the base Resonance Skill or Resonance Liberation.
- **Heavy Attack – Thunderoar: Uppercut:** When Prowess is full, pressing Jump performs Thunderoar: Uppercut (Electro DMG, consumes all Prowess) as an alternative to the Backstep path. Also triggered from Resonance Skill – Warrior's Blade when Prowess is full.
- **Dodge Counter – Thunderoar: Backstep (Ascendancy Full):** When Ascendancy is full, Normal Attack after a successful Dodge replaces the standard Dodge Counter with Dodge Counter – Thunderoar: Backstep (Electro DMG, Heavy Attack DMG). Can chain into Thunderoar: Spinslash.
- **Mid-Air Attack:** Consume STA to Plunge, dealing Electro DMG.
- **Mid-Air Dodge Counter:** Normal Attack after a successful Mid-Air Dodge for a Plunging Attack (Electro DMG, STA cost).

**Basic Attack Attribute Scaling (% of ATK, Lv.1 → Lv.10) — Stage 1 through 4 & Thunderoar: Spinslash:**

| Level | Stage 1 | Stage 2 | Stage 3 | Stage 4 | Thunderoar: Spinslash |
|-------|---------|---------|---------|---------|----------------------|
| 1     | ~34%    | ~36%    | ~43%    | ~56%    | ~408%                |
| 5     | ~44%    | ~47%    | ~56%    | ~73%    | ~531%                |
| 10    | ~66%    | ~71%    | ~84%    | ~110%   | ~800%                |

*Exact in-game per-level tables are not publicly standardized. Spinslash is confirmed to exceed 400% at Lv.1 (community, Wutheringlab). Lv.10 values are estimated using the standard ~1.5× Lv.1 multiplier curve. Consult the in-game skill screen for official values.*

## Augusta Resonance Skill: Warrior's Blade / Undying Sunlight
**Base Resonance Skill – Warrior's Blade:** Augusta performs a sweeping slash dealing Electro DMG. Restores 10% Ascendancy. Fully restores Prowess. Can trigger Thunderoar: Uppercut if Prowess was already full before casting.

**Enhanced Resonance Skill – Undying Sunlight (when Ascendancy is full, 100/100):**
A three-part aerial combo — the most important skill sequence in Augusta's kit:
- **Undying Sunlight: Strike** — Augusta charges forward on her blazing griffon, dealing Electro DMG. Provides access to Leap.
- **Undying Sunlight: Leap** — Augusta vaults skyward, dealing Electro DMG during the ascent.
- **Undying Sunlight: Plunge** — Augusta plunges from altitude and slams down her Broadblade, dealing Electro DMG classified as Heavy Attack DMG. Grants 1 stack of Majesty. This is the most important single hit in this chain and Augusta's highest-multiplier single attack (non-Liberation).

Post-S1: All three Enhanced RS parts become immune to interruption.

**Cooldown:** Warrior's Blade base skill has a standard cooldown; Undying Sunlight is only available when Ascendancy is full (not cooldown-gated independently).

**Resonance Skill Attribute Scaling (% of ATK, Lv.1 → Lv.10):**

| Level | Warrior's Blade | Undying Sunlight: Strike | Undying Sunlight: Leap | Undying Sunlight: Plunge |
|-------|----------------|--------------------------|------------------------|--------------------------|
| 1     | ~92%           | ~120%                    | ~60%                   | ~420%                    |
| 5     | ~120%          | ~156%                    | ~78%                   | ~547%                    |
| 10    | ~180%          | ~235%                    | ~117%                  | ~822%                    |

*Community-estimated ranges. Plunge is confirmed as Augusta's highest individual non-Liberation multiplier. Consult in-game for official per-level values.*

## Augusta Resonance Liberation: Sword of Eternal Oath / Sublime is the Sun
Augusta has two distinct Liberation states depending on Majesty stacks.

**Base Liberation — Sword of Eternal Oath (0–1 Majesty stack):**
Press and release Resonance Liberation. Augusta sweeps her Broadblade forward dealing Electro DMG classified as Heavy Attack DMG. Restores 40% Ascendancy.
- **Cost:** 125 Resonance Energy
- **Function:** A solid hit used during normal rotation to build Ascendancy faster. Can be used before the second Liberation is ready to maintain Ascendancy momentum.

**Enhanced Liberation — Sublime is the Sun (2 Majesty stacks):**
Hold Resonance Liberation. Costs 2 Majesty stacks (no Resonance Energy cost). Augusta generates the Ruler's Realm and enters the Sworn Allegiance state for 7 seconds.

**Sworn Allegiance State (7 seconds — time is stopped):**
- Time is completely stopped. Timers in Tower of Adversity and Whimpering Wastes pause during the full 7-second duration.
- Only Sublime is the Sun – Sunborne, Sublime is the Sun – Everbright Protector, and Dodge can be performed.
- Resonator switching is disabled during Sworn Allegiance.
- Augusta can walk on water without consuming STA in this state.
- **Sublime is the Sun – Sunborne (spam or hold Normal Attack):** Augusta swings 9 rapid Heavy Attack slashes, dealing Electro DMG each, classified as Heavy Attack DMG. Each hit is equal to 100% of Augusta's ATK.
- After 9 Sunborne hits, pressing Normal Attack or Resonance Liberation performs Sublime is the Sun – Everbright Protector.
- **Sublime is the Sun – Everbright Protector (finisher):** Augusta delivers a massive final blow dealing Electro DMG (Heavy Attack DMG). Ends Sworn Allegiance. Consumes all Crown of Wills stacks. All other Resonators are removed from the field.
- If Sworn Allegiance ends naturally (timer expires), Everbright Protector fires automatically.
- Players can early-cancel with Hold Liberation during Sworn Allegiance.

**Ruler's Realm (30s duration after Sublime is the Sun):**
- Persists for 30 seconds after Sublime is the Sun is cast, excluding the 7s of Sworn Allegiance itself.
- When Resonators in the team cast Intro Skill within Ruler's Realm: they gain a shield equal to 650 + 5% of Augusta's Max HP for 10 seconds (this effect does not stack).
- This "big shield" enables Crown of Valor stacks and Thunderflare Dominion's DEF ignore for teammates.

**Resonance Liberation Attribute Scaling (% of ATK, Lv.1 → Lv.10):**

| Level | Sword of Eternal Oath | Sunborne (per hit ×9) | Everbright Protector |
|-------|----------------------|----------------------|---------------------|
| 1     | ~180%                | 100% × 9 = 900%     | ~360%               |
| 5     | ~234%                | 100% × 9 = 900%     | ~469%               |
| 10    | ~353%                | 100% × 9 = 900%     | ~706%               |

*Sunborne multiplier (100% ATK per hit, 9 hits) is stated explicitly in-game and confirmed by multiple sources. Base Liberation and Everbright Protector scale with Liberation level. Total Liberation (Sunborne + Protector) accounts for ~53% of Augusta's total rotation damage (Wutheringlab).*

## Augusta Forte Circuit: Resource Management System
Augusta's Forte Circuit is the visual and mechanical representation of all three resources — Prowess (purple bar), Ascendancy (center circle/crown), and Majesty (gold blade icons) — displayed simultaneously.

**Prowess Generation:**
Basic Attacks, Heavy Attack – Steelclash, Mid-Air Attacks, Mid-Air Dodge Counter, Warrior's Blade, Dodge Counter, Dodge Counter – HA: Steelclash all generate Prowess. Prowess is instantly maxed by Intro Skill.

**Ascendancy Generation:**
Normal Attacks that deal damage generate Ascendancy. Intro Skill (+20%), Warrior's Blade (+10%), and Sword of Eternal Oath (+40%) also restore Ascendancy directly. The Enhanced RS combo (Undying Sunlight) consumes Ascendancy upon Plunge.

**Majesty Generation:**
Undying Sunlight: Plunge grants 1 Majesty. Augusta's Outro Skill effect (Battlesong of the Unyielding) grants 1 Majesty when the incoming Resonator casts their Outro Skill within the buff window. Blazing Valor (passive) restores 1 Majesty stack if Augusta has <1 after 4s out of combat.

**Crown of Wills Interaction:**
Crown of Wills (max 1 at S0, 2 at S1, 4 at S6) provides 15% Electro DMG Bonus per stack. Gained by casting Augusta's Outro Skill. Cleared by Everbright Protector. Also restored by Blazing Valor passive.

**Forte Circuit Attribute Scaling:**
The Forte Circuit does not have a separate DMG entry independent of the skills it unlocks. The key output is the Undying Sunlight chain (particularly Plunge) and the Thunderoar: Spinslash, both scaled under their respective skill categories above.

## Augusta Inherent Skill 1: Glory's Favor
When Augusta deals damage, she gains a shield equal to **350 + 2.5% of her Max HP** for 5 seconds, triggered once every 0.5 seconds. This shield is not transferred to incoming Resonators.

- At ~14,283 HP (Lv.90): Shield = 350 + 357 = ~707 HP
- Trigger rate: Every 0.5 seconds during active combat — near-permanent during full rotation
- Primary function: Enabling Crown of Valor echo stacks, Thunderflare Dominion's DEF ignore stacks, and the Ruler's Realm "big shield" for teammates
- Note: This shield does not meaningfully protect Augusta from damage — its strength is too low for that. It is a buff-trigger mechanic.

## Augusta Inherent Skill 2: Blazing Valor
When Augusta is out of combat for over 4 seconds, the following effects can trigger once every 4 seconds:
- If Majesty is less than 1 stack, restore 1 stack of Majesty.
- Fully restore all stacks of Crown of Wills.

This passive significantly reduces Augusta's ramp-up time, ensuring she frequently enters engagements with pre-loaded resources.

## Augusta Intro Skill: Stride of Goldenflare
**Definition:** Augusta leaps onto the battlefield and unleashes a sweeping strike, dealing Electro DMG. Upon landing:
- Fully restores Prowess (100/100 instantly)
- Restores 20% Ascendancy
- Post-S1: Grants 1 stack of Crown of Wills
- Post-S4: Increases ATK of all Resonators in the team by 20% for 30 seconds

**Intro Skill Attribute Scaling (% of ATK, Lv.1 → Lv.10):**

| Level | Intro Skill DMG |
|-------|----------------|
| 1     | ~80%           |
| 5     | ~104%          |
| 10    | ~157%          |

*Estimated from community sources. Confirm exact values in-game.*

## Augusta Outro Skill: Battlesong of the Unyielding
**Definition:** The next Resonator switched onto the field gains the following effects for 14 seconds (ends immediately if they are switched out):
- Gain **15% DMG Amplification for all Attributes** (applies to all damage types dealt by the incoming Resonator)
- If the Resonator with this buff casts their Outro Skill within the 14-second window → Augusta gains **1 stack of Majesty** and **1 stack of Crown of Wills**

This Outro mechanic is the lynchpin of Augusta's team rotation: the incoming teammate must chain their Outro Skill within 14 seconds to give Augusta the Majesty stack needed for her second, time-stopping Liberation. Without this interaction, Augusta needs to generate both Majesty stacks entirely from Undying Sunlight: Plunge (requiring two full Ascendancy cycles — significantly slower).

**Outro Skill Attribute Scaling:**
- DMG Amplification: 15% (flat, all-attribute) — does not scale with Outro level
- Buff duration: 14 seconds (flat)
- Consult in-game for any DMG values associated with the Outro animation itself.

---

## Augusta: Skill Upgrade Materials
Full Forte Upgrade (all skills Lv.1 → Lv.10):

- **Cadence Series** (Forgery Challenge drops): Lento Cadence, Adagio Cadence, Andante Cadence, Presto Cadence — approximately 25, 28, 40, and 57 respectively across all skills
- **When Irises Bloom** (Weekly Boss material from Fleurdelys): ~25 total for all skill upgrades
- **LF / MF / HF / FF Tidal Residuum** (enemy drops): Increasing quantities per tier
- **Waveworn Residue** (210, 226, 235, 239) — from Forgery Challenges
- **Shell Credits:** Approximately 2,030,000 total for full Forte upgrade (all skills to Lv.10)

**Skill Upgrade Priority (per Wutheringlab damage distribution analysis):**
1. **Resonance Liberation** (53% of total damage — highest priority)
2. **Basic Attack** (23% of total damage)
3. **Forte Circuit** (tied to Ascendancy chain — upgrade after above two)
4. **Resonance Skill** (can be upgraded later with minimal loss)
5. **Intro Skill** (lowest priority — upgrade last)

---

## Augusta: Resonance Chains (Sequence Nodes S1–S6)

## Augusta Resonance Chain S1: Light of the Eternal Sun
Each stack of Crown of Wills additionally increases Augusta's **Crit DMG by 15%**. The maximum stack of Crown of Wills is increased to **2**. Casting Intro Skill – Stride of Goldenflare now grants **1 stack of Crown of Wills**.

Additionally: Resonance Skill – Undying Sunlight: Strike, Leap, and Plunge are now **immune to interruption**.

*Impact: Approximately +16% total damage increase for Augusta. Provides up to 30% Electro DMG Bonus (2×15% from Crown of Wills) and adds 15% Crit DMG × 2 stacks. The interruption immunity on the Enhanced RS chain is a significant quality-of-life improvement, removing the need to carefully manage positioning during the aerial combo. Rated as high-value S1.*

## Augusta Resonance Chain S2: Radiant Crucible
Each stack of Crown of Wills **additionally** increases Augusta's Crit Rate by **20%**. For every 1% of Crit Rate over 100%, Augusta gains **2% Crit DMG**, up to **100% additional Crit DMG**.

*Impact: The highest-value individual node in Augusta's Resonance Chain. At 2 Crown of Wills stacks (S1 prerequisite), Augusta gains up to 40% bonus Crit Rate — easily capping or overcapping base Crit Rate depending on build. Overcapping Crit Rate then converts at 2:1 into Crit DMG (up to +100% Crit DMG maximum). This fundamentally changes Augusta's optimal echo setup at S2+, favoring Crit DMG over Crit Rate on the 4-Cost Echo (since Crit Rate is effectively abundant). Community consensus: S2 is one of the strongest, if not the strongest, single sequence node upgrades for any DPS character in Wuthering Waves as of Version 2.6–3.0.*

## Augusta Resonance Chain S3: Solar Dominion
The DMG Multiplier of the following skills is increased by **25%**:
- Heavy Attack – Thunderoar: Backstep
- Dodge Counter – Thunderoar: Backstep
- Heavy Attack – Thunderoar: Spinslash
- Heavy Attack – Thunderoar: Uppercut
- Resonance Skill – Undying Sunlight: Plunge
- Resonance Liberation – Sublime is the Sun: Sunborne
- Resonance Liberation – Sublime is the Sun: Everbright Protector

*Impact: A flat 25% multiplier on every single major damage skill — a straightforward but enormous damage node. This applies across her entire rotation's peak output, boosting all Prowess-enhanced Heavy Attacks, the Plunge, and both Liberation components simultaneously. Raw damage impact is significant — estimated +20–25% rotation DPS increase from S3 alone.*

## Augusta Resonance Chain S4: Conqueror's Banner
Casting Intro Skill – Stride of Goldenflare increases the **ATK of all Resonators in the team by 20%** for **30 seconds**.

*Impact: Team-wide 20% ATK buff with a 30-second window tied to Augusta's Intro Skill. In Augusta-centered teams, the Intro Skill fires at the start of each rotation cycle, making this effectively an uptime buff for the entire team. Has strong value in compositions with multiple ATK-scaling team members, though its value is naturally lower for non-ATK-scaling supports. Classified as a team support/utility node.*

## Augusta Resonance Chain S5: Blazing Aegis
The Shield provided by Inherent Skill – Glory's Favor is **increased by 50%**.

- New shield value: 525 + 3.75% of Augusta's Max HP (per trigger)
- At Lv.90: approximately 1,060 HP per shield application

*Impact: The weakest node for DPS — primarily a QoL and survivability node. The shield remains too small to meaningfully protect Augusta from significant damage in endgame content. Its primary value is marginally accelerating Crown of Valor and Thunderflare Dominion stack accumulation (since the stronger shield is still triggered on the same 0.5-second interval). This is the recommended skip node for players min-maxing.*

## Augusta Resonance Chain S6: Crown of Eternal Glory
Augusta can now hold up to **4 stacks** of Crown of Wills. When Augusta performs Heavy Attack – Thunderoar: Spinslash or Heavy Attack – Thunderoar: Uppercut, she obtains **1.5 stacks** of Crown of Wills. Augusta can only gain Crown of Wills stacks via this method once every 1.5 seconds.

Additionally: While casting Thunderoar: Spinslash or Thunderoar: Uppercut, **Thunder Rage** is triggered, dealing two instances of Electro DMG (Heavy Attack DMG). For every 1% of Crit Rate over **150%**, Augusta gains 2% Crit DMG (maximum +100% Crit DMG).

*Impact: At S6, the meta shifts substantially. With 4 Crown of Wills stacks and S2's overcap mechanic upgraded to trigger above 150% (instead of 100%), Augusta reaches her theoretical CRIT ceiling much faster and maintains it more consistently. The Thunder Rage procs add two additional Heavy Attack DMG instances per Spinslash/Uppercut. S6 provides approximately **+52% total damage** compared to S0 baseline (Wutheringlab analysis). The optimal 4-Cost Echo main stat shifts from Crit Rate to Crit DMG at S6, since Crit Rate is now abundantly generated internally.*

**Resonance Chain Priority:** S2 > S3 > S1 > S4 > S6 > S5

---

## Augusta: Echo Sets

## Augusta Echo Sets: Best Options
**Best Echo Set — Crown of Valor (3pc) + Void Thunder (2pc):**
- **Crown of Valor 3pc bonus:** Upon gaining a Shield, increase the Resonator's ATK by 6% and Crit DMG by 4% for 4 seconds. This effect can be triggered once every 0.5s, stacking up to 5 times. At max stacks: +30% ATK and +20% Crit DMG.
- **Void Thunder 2pc bonus:** +10% Electro DMG Bonus.
- **Why it works:** Augusta's Glory's Favor passive triggers a new shield every 0.5 seconds during combat — matching the Crown of Valor stack interval exactly. With proper rotation, she maintains 5/5 stacks for most of her active time, giving a substantial +30% ATK and +20% Crit DMG without any additional input.

**Alternative Echo Set — Void Thunder (5pc full set):**
- 2pc: +10% Electro DMG Bonus
- 5pc: After casting Intro Skill or Resonance Skill, deal 20% more Electro DMG for 15s
- Use when Crown of Valor is not yet fully farmed. Still very competitive, especially before Crown of Valor set is established.

## Augusta Echo Sets: Best Main Echo
**The False Sovereign (4-Cost Echo — Recommended):**
- Set: Crown of Valor (contributes to the 3pc bonus)
- Main Echo Skill: Transform into the False Sovereign and dash forward in a spinning strike, dealing 55.35% Electro DMG 4 times. Start with 2 charges; gain 1 charge every 8s, up to 2 charges.
- Passive bonus (equipped in main slot): +12% Electro DMG Bonus + 12% Heavy Attack DMG Bonus
- Upon casting Intro Skill, the False Sovereign is also summoned to deal 405% Electro DMG.
- **Why it's Best-in-Slot:** Provides two of Augusta's most important damage type bonuses simultaneously (Electro and Heavy Attack), has two charges enabling flexible rotation use, and offers a bonus Intro Skill proc.

**Alternative Main Echo — Impermanence Heron or other 4-Cost Havoc/Electro Echoes:** For players without False Sovereign, any 4-Cost Echo with Crit Rate main stat serves as an acceptable placeholder.

## Augusta Echo Sets: Echo Stat Priority

**4-Cost Echo Main Stat:**
- S0/S1: Crit Rate (priority — to hit the 70–80% Crit Rate target)
- S2–S5: Crit Rate or Crit DMG (flex depending on current substat rolls)
- S6: Crit DMG (Crit Rate naturally overcaps via Crown of Wills × 4 stacks + S2/S6 passive)

**3-Cost Echo Main Stats:** Electro DMG Bonus × 2 (NOT ATK% — using ATK% instead results in approximately 4% damage loss, equivalent to one effective substat)

**1-Cost Echo Main Stat:** ATK%

## Augusta Echo Sets: Substat Priority
1. Crit Rate / Crit DMG (balanced — equal value at S0; favor Crit DMG at S2+)
2. Heavy Attack DMG Bonus (notably higher value than ATK% for Augusta)
3. ATK%
4. Flat ATK (last resort)
5. Energy Regen: ~120% is sufficient for standard rotation; minimum needed for consistent Liberation cycling

---

## Augusta: Weapons

## Augusta Best Weapon: Thunderflare Dominion (Signature — 5-Star Broadblade)
- **Base ATK Lv.90 R1:** 675
- **Secondary Stat:** CRIT Rate 12.2%
- **Passive R1:** ATK +12%. Intro Skill or Resonance Skill → +20% Heavy Attack DMG for 15s. Gaining Shield → Heavy Attack DMG ignores 7.2% of target DEF for 7s, stacking up to 5×. Max DEF ignore: 36%.
- **Passive R5:** ATK +24%. HA DMG +40% for 15s. DEF ignore 12% per stack, up to 60% total.
- **Why Best-in-Slot:** Every facet of this weapon's passive synergizes with Augusta's kit. She casts Intro Skill and Resonance Skill every rotation. She gains shields every 0.5 seconds via Glory's Favor. The DEF ignore stacks to 5× within a few seconds of combat and remains near-permanently maintained. No other weapon provides this specific combination of Heavy Attack DMG% and DEF shred that Augusta can constantly use.

## Augusta Alternative Weapons

**Verdant Summit (5-Star Broadblade — Best F2P Alternative):**
- +48% CRIT DMG, +12% all-attribute bonus passive, +48% Heavy Attack DMG Bonus after Intro + Liberation combo
- Offers very competitive performance for Augusta especially after using her Liberation sequence, despite lacking Thunderflare's permanent DEF shred and ATK boost

**Aureate Zenith (Battle Pass Weapon — 4-Star):**
- +40% Crit DMG, boosts ATK and Heavy Attack DMG after Resonance Liberation
- Solid F2P option for players who invest in Battle Pass; best 4-star alternative if Verdant Summit is unavailable

**Autumntrace / Helios Cleaver (4-Star Alternatives):**
- Provide ATK% and Crit utility; competitive secondary options for early and mid-game builds

---

## Augusta: Team Composition Guide

## Augusta Best Team: Augusta + Iuno + Shorekeeper
**Role assignment:** Augusta (Main DPS) | Iuno (Sub-DPS / Heavy Attack Buffer) | Shorekeeper (Healer / Crit Buffer)

**Why this team:** Iuno provides a total of up to 90% DMG Amplification to Augusta through her kit — 40% All DMG + 50% Heavy Attack DMG — the latter being amplification that only Augusta can fully leverage via her shield-stacking interaction (Iuno's Full Moon Domain boosts Heavy Attack DMG when shields are generated). Shorekeeper provides CRIT Rate, CRIT DMG, team healing, and Stellarealm for additional utility. This is Augusta's highest-performing team as of Version 2.6–3.0.

**Team Rotation — Augusta + Iuno + Shorekeeper:**
1. Start with **Shorekeeper** → build Resonance and Concerto Energy via her internal combos → Activate Stellarealm → Switch to Iuno when her Intro is available
2. **Iuno** enters via Intro → immediately use Resonance Skill to activate Lunar Cycle → jump to enter New Moon state
3. In New Moon state → cast Liberation to fill Sentience points → 3 Basic Attacks + 2 Enhanced Resonance Skills to consume Forte energy
4. After consuming Sentience and filling Concerto Energy → Heavy Attack to activate Full Moon Domain → Switch to **Augusta**
5. **Augusta** enters → immediately perform Prowess-enhanced Heavy Attack combo → cast Echo Skill for Electro DMG
6. Cast Resonance Skill and Sword of Eternal Oath (base Liberation) + Heavy Attacks to build Ascendancy → perform Undying Sunlight chain (Strike → Leap → Plunge)
7. After Plunge grants 1st Majesty stack, Iuno's Outro effect should have provided the 2nd Majesty stack via Battlesong → Hold Liberation → Enter Sworn Allegiance
8. During Sworn Allegiance (7s): Attack 9× with Sunborne → cast Everbright Protector
9. After Sworn Allegiance: Additional Heavy Attack combo (HA + Stage 2–4)
10. Switch to Shorekeeper via Intro → Detonate Stellarealm
11. Repeat rotation

## Augusta Alternative Team 1: Augusta + Phrolova + Shorekeeper
**Role assignment:** Augusta (Main DPS) | Phrolova (Off-field DPS / Heavy Attack Amplifier) | Shorekeeper (Healer / Crit Buffer)

**Why this team:** Phrolova's Outro Skill grants 15% All-Type DMG Amplification + 25% Heavy Attack DMG Amplification. Augusta can fully leverage both. Phrolova's Hecate off-field damage adds independent DPS during Augusta's rotation windows. Shorekeeper handles sustain and provides CRIT Rate/DMG buffs.

**Team Rotation — Augusta + Phrolova + Shorekeeper:**
1. Start with **Shorekeeper** → build gauges → activate Stellarealm → switch to Phrolova
2. **Phrolova** → build 6 Volatile Notes via Basic Attack and Resonance Skill combos → once 6 notes ready, cast Scarlet Coda (enter Resolving Chord state)
3. Cast her Liberation during Resolving Chord → Hecate is summoned for off-field DPS → Switch to **Augusta** when Outro available
4. **Augusta** enters → Prowess-enhanced HA combo → Echo Skill → Resonance Skill + Liberation + HAs → Ascendancy to 100
5. Cast Undying Sunlight chain → Plunge → Hold Liberation → Enter Sworn Allegiance
6. Time stops for 7 seconds → 9× Sunborne → Everbright Protector
7. Augusta Heavy Attack combo → Switch back to Shorekeeper

*Recommended Echo Sets: Augusta — Crown of Valor (3pc) + Void Thunder (2pc); Phrolova — Dream of the Lost (3pc) + Havoc Eclipse (2pc)*

## Augusta Alternative Team 2: Augusta + Mortefi + Shorekeeper
**Role assignment:** Augusta (Main DPS) | Mortefi (Sub-DPS / Heavy Attack Buffer) | Shorekeeper (Healer)

**Why this team:** Mortefi's Outro grants 38% Heavy Attack DMG Amplification to the incoming Resonator for 14 seconds — the highest single Heavy Attack DMG buff among accessible supports for Augusta before Iuno was introduced. He also provides Fusion coordinated attack damage and ATK buffs. The team is straightforward and very effective.

**Team Rotation:**
1. **Shorekeeper** → build gauges → Stellarealm → switch to **Mortefi** (via Intro)
2. **Mortefi** → internal skill rotation to build Concerto Energy → activate Echo Skill buff for coordinated attacks → Outro Skill to give Augusta 38% Heavy Attack DMG buff
3. **Augusta** enters with 15% DMG Amp (Mortefi's Outro) + 38% Heavy Attack DMG → Prowess-enhanced Heavy Attacks → Echo Skill → RS + Liberation combos → Undying Sunlight Plunge → Sworn Allegiance
4. After Liberation: Heavy Attack combo → Outro → Mortefi re-enters → Repeat

---

## Augusta: DPS Benchmarks

## Augusta DPS Benchmarks: S0 to S6 Relative Performance
*All benchmarks at full Lv.90 build, Crown of Valor 3pc + Void Thunder 2pc, The False Sovereign 4-Cost, Thunderflare Dominion R1, optimal rotation. Team: Augusta + Iuno + Shorekeeper (or equivalent). Data sourced from Wutheringlab and community analysis.*

| Sequence | Relative Performance | Notes |
|----------|---------------------|-------|
| S0       | 100% (baseline)     | Fully functional. S0 + signature weapon is the recommended stopping point for most players. |
| S1       | ~116%               | +16% from Crown of Wills × 2 stacks (30% Electro DMG Bonus + 30% Crit DMG). Interruption immunity on Enhanced RS is a major QoL gain. |
| S2       | ~145–155%           | Most impactful single node. +40% Crit Rate from Crown of Wills x2 enables conversion to up to +100% Crit DMG when overcapped. Dramatically changes optimal echo stat setup. |
| S3       | ~175–185%           | +25% across all major skill multipliers — a flat and significant damage node. |
| S4       | ~185–195%           | Team-wide +20% ATK buff from Intro adds moderate DPS uplift across the whole team. |
| S5       | ~188–198%           | Minimal personal DPS gain — primarily survivability improvement. |
| S6       | ~152% of S0 (Wutheringlab: +52% total)| 4×Crown of Wills, Thunder Rage procs, and enhanced Crit overcap scaling. Optimal Crit DMG echo swap at S6. |

*Note: "Overall, S6 provides approximately a 52% damage increase for Augusta" — Wutheringlab (August 2025). Prydwen community grading: Augusta is T1 DPS as of Version 2.7–3.0 meta.*

**Teams used for benchmarks (per Game8 and Prydwen):**
- **Best-in-slot benchmark:** Augusta + Iuno + Shorekeeper
- **Alternative benchmark:** Augusta + Mortefi + Shorekeeper
- **Accessible F2P benchmark:** Augusta + Mortefi/Phrolova + Verina

---

## Augusta: Character Strengths and Weaknesses in Actual Gameplay

## Augusta: Strengths
- **Time-stop Liberation is uniquely powerful in timed endgame content:** Sworn Allegiance's 7-second timestop pauses Tower of Adversity and Whimpering Wastes timers. This allows Augusta to effectively deal free damage while also passively extending the timer's effective length — a gameplay advantage no other character replicates.
- **Complete invulnerability during Liberation:** The time-stop makes Augusta fully invulnerable to all damage during Sworn Allegiance. No dodge rolls, no timing required — pure offensive freedom.
- **Self-sufficient: strong F2P options:** Augusta performs competitively without her signature weapon. Verdant Summit is a strong and accessible alternative. She also functions with Mortefi as a support (a more accessible character than Iuno) without major losses.
- **Shield generation enables passive team buffs:** Gloria's Favor fires every 0.5s, granting near-permanent Crown of Valor stack uptime and Thunderflare Dominion DEF shred without any player input.
- **Decent team utility:** 15% all-attribute DMG Amplification Outro, post-S4 team-wide +20% ATK on Intro — adds meaningful support value alongside her DPS role.
- **Ruler's Realm team shielding:** Provides the entire team with access to the "big shield" for Crown of Valor stacking and Thunderflare's DEF ignore — extending her personal kit synergies to teammates.

## Augusta: Weaknesses
- **Backloaded damage is poor for AoE/multi-wave content:** Approximately half her total rotation damage is concentrated in the second Liberation (Sworn Allegiance). In Whimpering Wastes, if enemies die mid-Liberation or the next wave doesn't spawn until after timestop ends, a significant portion of damage is wasted on empty field.
- **Shields have no actual defensive value:** Glory's Favor shields (~707 HP at Lv.90, or ~1,060 at S5) provide negligible protection. They only function as buff triggers. Augusta is not protected from damage in any meaningful sense.
- **Incompatible with quickswap compositions:** Augusta's Outro effect requires the incoming Resonator to also Outro within 14 seconds to return Majesty — structurally demanding. Very difficult to integrate into quickswap teams that cycle characters rapidly.
- **Rotation is non-trivial:** Managing three resource bars (Prowess, Ascendancy, Majesty) simultaneously, chaining cancels correctly (Spinslash endlag cancel into RS or Liberation), and optimizing Echo Skill timing requires meaningful practice. She is explicitly labeled as a high execution-ceiling character in multiple community guides.
- **Shields do not prevent interruption:** Despite having shields active, Augusta can be staggered and interrupted by heavy enemy attacks. Players must still dodge appropriately or use positioning to maintain their rotation.
- **Intro Skill–dependent Outro chain:** Generating the 2nd Majesty stack requires the incoming Resonator to cast their Outro during Augusta's buff window (14s). This mandates bringing characters with reliable, short-cycle Outro Skills (Iuno, Mortefi, Phrolova), limiting team flexibility somewhat.

---
## Sources
- Wuthering Waves Fandom Wiki – Augusta: https://wutheringwaves.fandom.com/wiki/Augusta
- Prydwen.gg – Augusta Guide and Build: https://www.prydwen.gg/wuthering-waves/characters/augusta/
- Game8.co – Augusta Best Builds and Teams: https://game8.co/games/Wuthering-Waves/archives/524890
- Wutheringlab.com – Augusta Build: https://wutheringlab.com/character/augusta-build/
- Wuthering.gg – Augusta Build and Info: https://wuthering.gg/characters/augusta
- LootBar.gg – Augusta Kit Revealed: https://lootbar.gg/blog/en/wuthering-waves-augusta-kit.html
- LootBar.gg – Augusta Build Guide: https://lootbar.gg/blog/en/wuthering-waves-augusta-build-guide.html
- Sportskeeda – Augusta Resonance Chain Guide: https://www.sportskeeda.com/esports/wuthering-waves-wuwa-augusta-resonance-chain-guide
- Destructoid – Best Augusta Build: https://www.destructoid.com/the-best-augusta-build-in-wuthering-waves-best-weapons-echoes-and-team-compositions/
- Genshin-Builds – Augusta Build: https://wutheringwaves-builds.com/character/augusta/
- WuWaCompanion – Augusta Stats: https://wuwacompanion.com/en/database/resonators/augusta
- FdayTalk – Augusta Build Guide: https://www.fdaytalk.com/augusta-wuthering-waves-build/
- Genshin-Builds – Augusta Teams: https://genshin-builds.com/en/wuthering-waves/characters/augusta
- OSLink – WuWa 2.6 Augusta Leaks: https://www.oslink.io/blog/news/wuthering-waves-augusta-kit.html
