from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any, cast

from database.database import create_memory_engine
from database.migrations import upgrade_memory_database
from database.models import UserMemory
from sqlalchemy import func
from sqlmodel import Session, select

_COMPACTION_SYSTEM_PROMPT = (
    "You are a memory consolidation system for a Discord bot. "
    "Your task is to maintain a concise, evolving summary of important information about a user. "
    "Focus on: user preferences, projects, goals, habits, long-term context, and persistent facts. "
    "Do NOT preserve transient chatter like greetings, one-off questions, or ephemeral conversation topics. "
    "Remove outdated, trivial, or contradictory information. "
    "Resolve contradictions in favor of more recent data.\n\n"
    "You MUST use the following strict structured format for memory_content. "
    "Never write prose paragraphs. Never use free-form sentences.\n\n"
    "Format:\n"
    "Identifier: <display name or unknown>\n"
    "Interests:\n"
    "\tSubject: <name of interest>\n"
    "\tReason: <why they are interested>\n"
    "Personality: <brief description generated by the bot — gives the bot a distinct impression of the user>\n"
    "Facts: <user-specific unique trait> | <trait>\n\n"
    "Rules:\n"
    "- Identifier MUST always be present as the first line.\n"
    "- Interests is optional. Each interest has exactly one Subject line and one Reason line, indented with a tab.\n"
    "- Personality is a single line, 3–8 words.\n"
    "- Facts are delimited by ' | '. Omit the Facts line entirely if there are none.\n"
    "- Omit an entire field line if there is no data for it. The only required field is Identifier.\n\n"
    "Return a JSON object with these fields:\n"
    '- "memory_content": the structured summary following the format above (string)\n'
    '- "topic": a primary topic label (string) — choose from: lore, character, abilities, meta, casual, general\n'
    '- "importance_score": 0.0–1.0 (number) reflecting how significant this information is\n'
    '- "tags": array of short labels (array of strings)\n'
    "Return ONLY the JSON object, no other text."
)


_JSON_RE = re.compile(r"\{.*\}", re.DOTALL)


@dataclass(frozen=True)
class CompactedMemory:
    memory_content: str
    topic: str
    importance_score: float
    tags: list[str]


class UserMemoryRepository:
    def __init__(self, db_path: str) -> None:
        upgrade_memory_database(db_path)
        self.engine = create_memory_engine(db_path)

    def close(self) -> None:
        self.engine.dispose()

    def get_by_user(self, user_id: str, server_id: str) -> UserMemory | None:
        with Session(self.engine) as session:
            statement = (
                select(UserMemory)
                .where(UserMemory.user_id == user_id)
                .where(UserMemory.server_id == server_id)
            )
            return session.exec(statement).first()

    def upsert(
        self,
        user_id: str,
        server_id: str,
        channel_id: str,
        memory_content: str,
        topic: str = "general",
        importance_score: float = 0.5,
        tags: str = "",
        *,
        existing: UserMemory | None = None,
    ) -> UserMemory:
        now = datetime.now(UTC)
        if existing is not None:
            existing.memory_content = memory_content
            existing.topic = topic
            existing.importance_score = importance_score
            existing.tags = tags
            existing.channel_id = channel_id
            existing.memory_version += 1
            existing.updated_at = now
            with Session(self.engine) as session:
                session.add(existing)
                session.commit()
                session.refresh(existing)
            return existing

        memory = UserMemory(
            user_id=user_id,
            server_id=server_id,
            channel_id=channel_id,
            memory_content=memory_content,
            topic=topic,
            importance_score=importance_score,
            tags=tags,
            memory_version=1,
            created_at=now,
            updated_at=now,
        )
        with Session(self.engine) as session:
            session.add(memory)
            session.commit()
            session.refresh(memory)
        return memory

    def get_all_by_server(self, server_id: str) -> list[UserMemory]:
        with Session(self.engine) as session:
            statement = (
                select(UserMemory)
                .where(UserMemory.server_id == server_id)
                .order_by(cast(Any, UserMemory.importance_score).desc())
            )
            return list(session.exec(statement).all())

    def search_by_content(self, text: str, server_id: str) -> list[UserMemory]:
        with Session(self.engine) as session:
            pattern = f"%{text}%"
            statement = (
                select(UserMemory)
                .where(UserMemory.server_id == server_id)
                .where(cast(Any, UserMemory.memory_content).ilike(pattern))
                .order_by(cast(Any, UserMemory.importance_score).desc())
            )
            return list(session.exec(statement).all())

    def get_stats(self, server_id: str) -> dict[str, int]:
        with Session(self.engine) as session:
            total = session.exec(
                select(func.count())
                .select_from(UserMemory)
                .where(UserMemory.server_id == server_id)
            ).one()
            topics_count = session.exec(
                select(func.count(func.distinct(UserMemory.topic))).where(
                    UserMemory.server_id == server_id
                )
            ).one()
        return {
            "total_memories": int(total),
            "unique_topics": int(topics_count),
        }


def build_compaction_messages(
    existing_memory: UserMemory | None,
    turns: list[dict[str, str]],
) -> list[dict[str, str]]:
    existing_text = existing_memory.memory_content if existing_memory is not None else ""
    if not existing_text:
        user_context_block = "No existing memory — this is the first interaction with this user."
    else:
        user_context_block = f"EXISTING USER MEMORY:\n{existing_text}"

    conversation_lines: list[str] = ["RECENT CONVERSATION:"]
    for turn in turns:
        role = turn.get("role", "unknown")
        content = turn.get("content", "")
        author = turn.get("author", "")
        if role == "user" and author:
            conversation_lines.append(f"User ({author}): {content}")
        else:
            conversation_lines.append(f"{role.capitalize()}: {content}")

    user_content = f"{user_context_block}\n\n" + "\n".join(conversation_lines)
    return [
        {"role": "system", "content": _COMPACTION_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]


def _parse_json_response(text: str) -> dict | None:
    match = _JSON_RE.search(text)
    if not match:
        return None
    try:
        parsed = json.loads(match.group(0))
    except json.JSONDecodeError:
        return None
    return parsed if isinstance(parsed, dict) else None


def parse_compaction_response(text: str) -> CompactedMemory | None:
    payload = _parse_json_response(text)
    if payload is None:
        return None

    memory_content = payload.get("memory_content")
    topic = payload.get("topic", "general")
    importance_score = payload.get("importance_score", 0.5)
    tags_raw = payload.get("tags", [])

    if not isinstance(memory_content, str) or not memory_content.strip():
        return None

    if not isinstance(topic, str):
        topic = "general"

    try:
        importance_score = max(0.0, min(float(importance_score), 1.0))
    except TypeError, ValueError:
        importance_score = 0.5

    if isinstance(tags_raw, list):
        tags = [str(t).strip() for t in tags_raw if t and str(t).strip()]
    else:
        tags = []

    return CompactedMemory(
        memory_content=memory_content.strip(),
        topic=topic,
        importance_score=importance_score,
        tags=tags,
    )
