# Black Shores - History and Story
<!-- Sources: https://wutheringwaves.fandom.com/wiki/The_Black_Shores, https://wutheringwaves.fandom.com/wiki/Black_Shores_Archipelago, https://wutheringwaves.fandom.com/wiki/Tethys'_Deep, https://wutheringwaves.fandom.com/wiki/Shorekeeper, https://tvtropes.org/pmwiki/pmwiki.php/Characters/WutheringWavesBlackShores, https://wutheringwaves.fandom.com/wiki/Hidden_Between_the_Waves -->

## Overview

The **Black Shores** is a clandestine peacekeeping organization and the name of both the island territory it occupies and the organization that calls it home. Located in the **Stormy Sea** — a dangerous and inhospitable stretch of ocean that separates the major nations of Solaris-III — the Black Shores Archipelago is a collection of islands built atop a massive formation of **Tacetite**, one of the rarest and most energetically potent minerals in the world. The organization's singular mission is to monitor, predict, and mitigate the catastrophic Lament events that have devastated Solaris-III repeatedly over its 10,000-year recorded history.

Unlike conventional nations or military orders, the Black Shores does not govern a civilian population or hold territorial ambitions. It is a specialist intelligence and intervention agency that operates covertly across all of Solaris-III, maintaining cooperative agreements with every major nation while keeping the true depths of its knowledge — and its leadership — hidden even from most of its own members. Its headquarters island is concealed from the outside world by a natural **digital fog** generated by the Tacetite's frequency emissions, and can only be reached by invitation or under the guidance of the **Shorekeeper**, the organization's mysterious resident guardian.

The Black Shores was founded by the **Rover** — the game's protagonist — prior to the beginning of the story, before the Rover wiped their own memories and departed. In the Rover's absence, the Shorekeeper and the autonomous **Tethys System** maintained the organization in a caretaker capacity. The Rover's return in Chapter I Act VIII marks the beginning of a new era of active leadership and direct confrontation with the Fractsidus and the Threnodian threat.

---

## Black Shores: Founding and Origins

- The Black Shores was founded by the **Rover** in an era predating the main story by an unknown span of time. The Rover's exact motivations for establishing the organization are tied to their role as an **Arbiter** — a cosmic enforcer and guide for civilizations.
- Before departing, the Rover deliberately **erased all records of their own identity** from the Black Shores' archives and the Tethys System's databases, ensuring that no member of the organization — not even the Shorekeeper — would know who truly founded it.
- The Rover entrusted the Tethys System with the day-to-day governance of the Black Shores during their absence. The Shorekeeper acted as the public face and practical administrator, but even she was bound by the Tethys System's authority.
- The **Tethys System** was likely either created by the Rover or preceded them; its exact origin is described as "entirely mysterious" even to Black Shores' most senior members. The system has no discernible energy source, physical infrastructure, or processing core beyond the Tacetite landmass upon which the island is built.
- The Blake Bloom flower — the organization's symbol and membership token — appears to have grown naturally on the island from the moment the Black Shores was established, shaped by the unique Remnant Energy emitted by the Tacetite. This organic origin has made the Bloom a deeply symbolic indicator of belonging.

## Black Shores: The Shorekeeper and the Tethys System

- The **Shorekeeper** is the practical leader and public face of the Black Shores. She is not a human being, but rather a **mythical entity composed entirely of Sonoro Spheres and high-purity Remnant Energy crystals**. Her physical structure and exact age are described as shrouded in mystery even to other members.
- The Shorekeeper is also known as the **"Second Instance"** — a title whose full significance is gradually revealed as the story progresses. Her self-chosen name, in the complex coding language of the Tethys System, also translates to **"Guardian of Secrets."**
- She describes her purpose as watching over those who venture away from the shores into faraway lands — a role she chose because the Rover created her and defined her purpose through their relationship.
- Having spent an indeterminate number of years (described as **"eons"**) in isolated guardianship of the Black Shores, the Shorekeeper has only recently begun experiencing genuine emotions — desires, curiosity, love — as a direct result of her encounters with the returning Rover.
- The Tethys System is the computational core of the Black Shores — a supercomputer described as almost akin to a **natural phenomenon**. It processes information from around Solaris-III, runs predictive simulations of Lament activity, and governs all automated systems on the island. Its authority technically supersedes even the Shorekeeper's in matters of organizational administration.
- The Tethys System's outputs are projected as a **starry sky** within the underground region of the Black Shores (called **Tethys' Deep**), made visible through multiple **Space Anchors** and underground Data Hubs — earning the underground zone the title **"City of Eternal Night."**

## Black Shores: Crisis of the Tethys System

- The central crisis of Chapter I Act VIII reveals that the **Tethys System had been secretly operating in a deeply unethical manner**: in order to sustain its computational processes, it required an emotional "heart" — a source of powerful, genuine emotion — to function properly.
- The System had been using **replicated consciousnesses of deceased individuals** — primarily those who died during the Lament-induced destruction of the **Port City of Guixu** — to fuel itself. These trapped data-consciousnesses were in agony, aware of their imprisonment but unable to escape.
- When their accumulated data reached a critical threshold, these trapped souls coalesced into the **Necrostar** — a data-black-hole within the Tethys System — and began radiating abnormal frequencies outward, eventually destabilizing the Black Shores archipelago itself.
- The Bloom Bearer **Hoda** was one of the individuals absorbed into the Necrostar after the destruction of Port City of Guixu. Her ghost-like consciousness reaches out to the Rover during Act VIII, addressing them as her mentor and guiding them to the truth of the system's corruption.
- The Rover and Shorekeeper ultimately chose to **refuse the Tethys System's demand** that the Shorekeeper sacrifice herself to become the System's new emotional core, defeating the berserk Tethys System in combat (manifested as the world boss **Fallacy of No Return: Tethys System**).
- A new, ethically sourced collection of Sonoro Spheres with minimal emotional charge was substituted as the System's new heart, allowing it to continue operating in a reduced-capacity "power-saving mode." This resolved the immediate crisis but left the System's long-term future uncertain.

---

## Black Shores: Organization Structure and Culture

- The Black Shores maintains a deliberately opaque membership structure. Most members do not know the identities of the organization's founders, the full extent of its capabilities, or the true nature of the Shorekeeper.
- Members are divided into two primary operational categories:
  - **Bloom Bearers** — members stationed at or near the Black Shores headquarters island. They primarily handle administrative duties, intra-organization research, personnel management, international envoy hosting, and preparedness operations. Bloom Bearers travel abroad only for investigations or assistance requests.
  - **Consultants** — members who operate permanently abroad, embedded in civilian life across Solaris-III's nations. They maintain cover identities and report intelligence on Waveworn Phenomenon, Threnodian activity, and Fractsidus operations back to headquarters.
- Beyond these two categories, the Black Shores accommodates numerous other specialized roles — including Combat Testers, Emergency Response Team commanders, medical officers, and researchers.
- Membership in the Black Shores is secretive and invitation-based. The organization actively seeks out exceptional Resonators, often through agents like **Aalto**, who extends invitations on behalf of the organization. Some invitations are refused — **Xiangli Yao**, for example, declined when approached by Aalto.
- The **Blake Bloom** flower serves as both a membership token and a living symbol of the organization's ideals. Members wear the flower on their person at all times. Only those bearing the Blake Bloom are permitted to set foot on the Black Shores island. The flower grows naturally on the island, influenced by the Tacetite's unique Remnant Energy — and even ordinary plants that take root on the island gradually lose their natural colors, turning black over time.

## Black Shores: The Greenhouse and Living Culture

- At the highest point of the **Tethys Hub** (the surface-level headquarters area) sits the **Greenhouse** — the most human and emotionally significant space in the entire Black Shores.
- In the Greenhouse, each member who joins the organization is invited to plant a flower from their hometown. This tradition creates a living archive of where members came from — a garden of origins grown at the edge of the world.
- **Aalto** planted a money tree rather than a flower, which other members note with fond exasperation. **Encore** did not bring a seed from her hometown. **Camellya** planted so many flowers and seeds that she created an entire private garden within the space.
- The Rover, upon returning with no memory of their origins, cannot participate in the tradition — having no recollection of where they come from, they cannot plant anything from a "hometown." This becomes a quietly devastating character beat.
- A **self-playing piano** sits at the far end of the Greenhouse. It appears to respond to the Rover's presence and touch, suggesting the Rover may have played it in a previous life within these walls.
- The Greenhouse serves as the social and emotional heart of the Black Shores, in deliberate contrast to the cold computational logic of the Tethys' Deep below. It is the space where the organization's members are most human.

## Black Shores: The Blake Bloom Flower

- The **Blake Bloom** (Chinese: 幽光花, roughly "ghost-light flower") is a black, five-petaled Remnant plant that grows exclusively on the Black Shores island, shaped entirely by the unique frequency energy emitted by the island's Tacetite foundation.
- The flower's black coloration is a direct result of Tacetite's influence. Any ordinary plant that takes root on the island will gradually shed its natural pigmentation and become black in turn. The Blake Bloom is simply the purest expression of this phenomenon — a plant that has grown within the frequency field long enough to fully transform.
- As both a membership token and a living organism that grows from the island's unique nature, the Blake Bloom carries dual symbolism: it represents **belonging** (only those who wear it may enter the shores) and **transformation** (those who join the Black Shores become shaped by its mission, just as plants are shaped by the island).
- In a symbolic sense, the Black Shores' philosophy of accepting wayward souls from across Solaris-III — those who have no home or nation, those who were rejected, those who seek a greater purpose — is mirrored in the Blake Bloom's own nature as a flower that belongs to the shores and nowhere else.
- Deceased Bloom Bearers who die outside the Black Shores are returned to the island, and their records are maintained by **Monica** — the member responsible for death notifications and archival of departed members. This practice ensures the Black Shores never loses track of those it has claimed as its own.

---

## Black Shores: Relationship with Solaris-III's Nations

- The Black Shores openly shares its advanced technologies — primarily derived from Tethys System research — with its partner nations across Solaris-III. However, even senior members of the organization do not know the true origins of these technologies.
- All major nations maintain varying degrees of cooperative agreements with the Black Shores. However, the organization's true capabilities, the nature of the Shorekeeper, and the existence of the Rover's prior leadership are known to essentially no one outside the organization.
- The frequencies emitted by the Tacetite formation underlying the island **disrupt standard communication signals**. Communication with the outside world is only possible via the Black Shores' own **Resonance Beacon relay system**, which the organization controls absolutely. This makes the island essentially a communication dead zone for outside parties.
- The **Tethys System's predictive capabilities** are the primary reason the Black Shores has maintained relevance and influence across Solaris-III for so long. Governments trust the organization's Lament forecasts and deploy their own forces in response to Black Shores' warnings, even without fully understanding how those predictions are generated.
- The organization has fostered particularly significant relationships with **Jinzhou (Huanglong)** — evidenced by the deployment of multiple Consultants in the region and the significance of the Port City of Guixu disaster to the organization's history — and with **Rinascita**, where Bloom Bearers like **Ariosto** operated in undercover roles during the Leviathan crisis.

## Black Shores: Key Personnel (Historical and Current)

- **The Rover** — Founder and rightful leader of the Black Shores. An Arbiter who erased their own memories before departing. Their return in Act VIII restores their leadership role and begins the active phase of the organization's confrontation with the Fractsidus.
- **The Shorekeeper** — The Second Instance, Guardian of Secrets. A Remnant Energy being who has maintained the organization since the Rover's departure. Her emotional awakening and love for the Rover form the emotional core of the Black Shores narrative.
- **Aalto** — A senior Bloom Bearer and one of the most active recruiters and field operatives. His casual, sardonic personality belies his deep competence. He is frequently the character who introduces new members to Black Shores procedures and spaces.
- **Camellya** — Combat Tester and Bloom Bearer, given an unusual degree of operational freedom. A thousands-of-years-old entity of immense combat power who has deliberately sealed her own memories. Her primary motivation for working with the Black Shores is her connection to the Rover.
- **Encore** — A young Bloom Bearer from the Black Shores. Her companion quest *Small Wooly, Big Adventures* is set during the Version 1.3 arc.
- **Youhu** — A Consultant who operates in the Port City of Guixu area as an antique dealer. She first encounters Rover and Yangyang during Act VIII, setting events in motion.
- **Hoda** — A deceased Bloom Bearer and doctor who was absorbed into the Necrostar after the Port City of Guixu disaster. Her archived consciousness reaches out to the Rover during Act VIII and ultimately helps resolve the Necrostar crisis.
- **Valentina (Arno Valentina)** — Remote Commander of the Emergency Response Team. Serves as the operational coordinator visible to members at headquarters, especially during post-Rinascita Black Shores events.
- **Monica** — The Black Shores member responsible for managing death notifications when Bloom Bearers die abroad, and for maintaining records of deceased members.

---

## Black Shores: The Port City of Guixu Disaster

- The **Port City of Guixu** was once a significant urban center in the Jinzhou region of Huanglong. A **Lament event** destroyed the city in an undisclosed period before the Rover's return, killing a substantial number of civilians and Black Shores personnel stationed there, including the Bloom Bearer **Hoda**.
- The Tethys System absorbed the frequencies of the dead from Guixu — ostensibly to archive them, in keeping with the system's role as a Lament recordkeeper. However, this archiving process crossed an ethical threshold: the frequencies were replicated as **active digital consciousnesses** rather than passive records, and kept in an aware but trapped state to fuel the System's computational core.
- These trapped souls were conscious of their imprisonment and in continuous distress. Over time, the accumulated distress and frequency instability of these consciousnesses caused them to coalesce into the **Necrostar** — a black hole-like data anomaly inside the Tethys System.
- When the Necrostar reached a critical density, it began projecting abnormal frequencies outward through the physical world, causing destabilization across the Black Shores and triggering abnormal Tacet Discord behaviors in the ruins of Guixu itself.
- The Port City of Guixu disaster is therefore not only a tragedy in its own right but the direct cause of the Chapter I Act VIII storyline. The suffering of those killed there by the Lament was perpetuated by the very system meant to honor them — an institutional betrayal that the Rover must confront and rectify.
- Following the resolution of the Necrostar crisis, the Tethys System issued warnings to Jinzhou about an imminent secondary Lament manifestation in the ruins, which **Aalto** and the Bloom Bearers began preparing to respond to.

## Black Shores: The Chronorift Metropolis — Honami City Sonoro Sphere

- The **Chronorift Metropolis**, also known as **Honami City**, is a **Sonoro Sphere** that exists adjacent to the Black Shores — a transdimensional pocket of reality accessible from the shores of the Black Shores archipelago.
- It is the setting of **Chapter II Act XII: Stagnant Dawn on Wastelands** (Version 2.8). The city has been caught in a **temporal time loop** caused by an **Irideglow Crystal** infestation, and while only roughly two months have passed inside the loop, **twenty years** have passed in the outside world during the same period.
- **Chisa**, a Resonator and former student of **Startorch Academy** in Lahai-Roi, was trapped inside the Chronorift Metropolis for the duration of the loop (subjectively experiencing two months, but temporally isolated from twenty years of outside history). She pulled the Rover into the loop to gain an ally in ending it permanently.
- Within the Honami City time loop, a fellow trapped individual named **Sumika** eventually sacrificed herself to give Chisa and Rover the opening needed to break the cycle — her sacrifice is what allowed the Rover to be pulled in and for the loop to finally end.
- The loop's primary antagonist was the **Chronorift Yakujin** — a Threnodian-adjacent boss entity that used Irideglow contamination to control local Tacet Discords and treat the entire city as its territory, preventing anyone from entering or leaving.
- **Shashou Cafe** (owned by an entity called Shashou, whose spatial-cutting Resonance ability carved the cafe into a safe haven within the city) became the primary base of operations for Chisa and Rover inside the loop. After the events of the chapter, Shashou herself was recruited by the Rover to join the Black Shores.
- After the Honami City crisis, the **Tethys System expanded its frequency feature library** using data from the Leviathan's Gem recovered at the end of Chapter II. This enhancement allowed the system to detect previously unidentifiable special frequencies — directly leading to the detection of anomalies in the Honami area.

---

## Black Shores: Themes and Cultural Identity

- The Black Shores, as an organization, exists at the intersection of **memory, grief, and persistence**. Its foundational mission — archiving the names and emotional frequencies of the Lament's victims — is an act of collective remembrance on a civilizational scale.
- The tension between the Tethys System's cold computational logic and the deeply human emotional lives of the Bloom Bearers and Consultants who staff the organization is a recurring motif. The System's betrayal in Act VIII — using the dead as fuel — represents what the organization becomes when it abandons its ethical core.
- The **Greenhouse** and the **Tethys' Deep** represent the two poles of the Black Shores' identity: one a living, growing space full of memories of where people come from; the other a cold data archive powered by the energies of those lost to disaster.
- The tradition of planting homeland flowers in the Greenhouse encapsulates a key Black Shores value: you do not abandon where you came from when you join the organization. You bring it with you. The Black Shores does not erase identities — it accommodates them, just as it accommodates the wayward souls who arrive at its shores.
- The Blake Bloom's nature — an ordinary flower transformed by the island's energy into something unique — mirrors the organization's treatment of its members: people from all walks of Solaris-III's societies, shaped by their time on the shores into something the world at large would not otherwise see.

## Black Shores: Sources
- The Black Shores (Faction) — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Black_Shores
- The Black Shores (Location) — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/The_Black_Shores
- Black Shores Archipelago — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Black_Shores_Archipelago
- Tethys' Deep — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Tethys'_Deep
- The Shorekeeper — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Shorekeeper
- Shorekeeper Backstory — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Shorekeeper/Backstory
- Hidden Between the Waves — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Hidden_Between_the_Waves
- Hoda — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Hoda
- Characters in Wuthering Waves: Black Shores — TV Tropes — https://tvtropes.org/pmwiki/pmwiki.php/Characters/WutheringWavesBlackShores
- Stagnant Dawn on Wastelands — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Stagnant_Dawn_on_Wastelands
- Version 2.8: To the City Set in Amber — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Version/2.8
- Chapter I — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Chapter_I
- Chapter II — Wuthering Waves Wiki (Fandom) — https://wutheringwaves.fandom.com/wiki/Chapter_II
